### ISSUE TITLE
Session history is not correctly restored on Android

### ISSUE THREAD

**Issue by buttercookie42** [jmozmoz/tabPreLoader#1]
Note that I'm not actively using this add-on, but I was looking through AMO in how far there were add-ons for Fennec using session store-related functionality and I noticed two complaints about tabs failing to properly load.

Assuming those complaints were referring to running this add-on on Android, your code is [only reloading the current URL in the session history](https://github.com/jmozmoz/tabPreLoader/blob/3743d5aba5de7bd2f35d192d301089b2dab92dc8/lib/main.js#L118), but fails to restore all other session store data for that tab - compare the [code flow of the session store itself](https://dxr.mozilla.org/mozilla-central/rev/0d823cf54df53e0cea75a74adebace956bd333d8/mobile/android/components/SessionStore.js#752) when restoring zombie tabs.

**Comment by jmozmoz** [comment]
You are right, especially the history is lost. Unfortunately at the moment I do not know how to implement this without the need to re-implement SessionStore.js. Is there a way to access it from a SDK add-on?

**Comment by buttercookie42** [comment]
Unfortunately you're right, the required functionality currently isn't exposed at all outside the session store, so not even non-SDK add-ons could access it. However unless I'm mistaken, in the end you're accessing the internal tab objects anyway and not some SDK abstraction, right?

In that case, [exposing that functionality](https://dxr.mozilla.org/mozilla-central/rev/b3774461acc6bee2216c5f57e167f9e5795fb09d/mobile/android/components/SessionStore.idl) and adding it to the [internal tab object](https://dxr.mozilla.org/mozilla-central/rev/b3774461acc6bee2216c5f57e167f9e5795fb09d/mobile/android/chrome/content/browser.js#3439) should be quite simple.

The biggest issue is probably rather the impending move to WebExtensions (even though Fennec is rather lagging behind there), which puts a question mark on any added functionality for current add-ons, although it might not be too bad in this case. If you want to file a bug and CC me (:JanH), I can do the required changes if there no objections appear. You might also want to add a second bug under Toolkit/WebExtensions:Untriaged, so this doesn't get forgotten when tabs functionality is implemented for WebExtensions on Android.

**Comment by buttercookie42** [comment]
[Bug 1333046](https://bugzilla.mozilla.org/show_bug.cgi?id=1333046) for the quick solution now and [Bug 1333047](https://bugzilla.mozilla.org/show_bug.cgi?id=1333047) for later WebExtensions.

**Comment by jmozmoz** [comment]
Thank you very much for filing the bugs.

**Comment by buttercookie42** [comment]
This should be fixed in Firefox shortly - once it's landed, something like this should probably work:
```javascript
if (xt.unzombify) {
  xt.unzombify();
} else {
  var data = gBrowser2.__SS_data;
  // rest of your old code ...
}

**Comment by jmozmoz** [comment]
Take you very much for your support. I will test it with a nightly build on Android and the push a new release to AMO.

**Comment by jmozmoz** [comment]
I have uploaded version 0.7.1beta2 implementing your suggested changes.
