### ISSUE TITLE
Migrate to WebExtensions

### ISSUE THREAD

**Issue by Keith94** [jmozmoz/tabPreLoader#2]
Are there plans to migrate the add-on to WebExtensions API, so it can continue working in Firefox 57 and later?

**Comment by jmozmoz** [comment]
If possible with the WebExtensions API, then I would like to update it. But I think, I have to wait for the implementation of these bugs: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1322485
https://bugzilla.mozilla.org/show_bug.cgi?id=1284886

Or do you know any other way to achieve this?

**Comment by Keith94** [comment]
>Or do you know any other way to achieve this?

Nope, I just wanted to open a bug here for tracking.
Good to hear that it may continue working in the future.

**Comment by yfdyh000** [comment]
@jmozmoz I don't think you need that two bugs, they are unload instead of load tabs.
You may need the https://bugzilla.mozilla.org/show_bug.cgi?id=1372442, or another event for the browser started instead of extension is activated, and how to activate tabs.

**Comment by jmozmoz** [comment]
I think I need the discarded attribute as described here, to see if a tab has been unloaded/not loaded yet after a restart?
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/Tab
But it looks like Firefox is not supporting it (yet?) I think it should be implemented with this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1322485

**Comment by yfdyh000** [comment]
You are right, looks I misunderstood its functionality.

**Comment by jmozmoz** [comment]
The real firefox bug which must be fixed is this one: https://bugzilla.mozilla.org/show_bug.cgi?id=1377733
(and at least there is some progress)

**Comment by jmozmoz** [comment]
I have uploaded an WebExtension version into the Developer Channel on AMO (0.8.0beta1). Please test it.

**Comment by Keith94** [comment]
@jmozmoz It works really well, nice job. :)
