### ISSUE TITLE
Downloading xpi for previous versions?

### ISSUE THREAD

**Issue by LafinJack** [jmozmoz/tabPreLoader#4]
Hi there, I'm not too familiar with Github, but I can only seem to download the .zip or .tar.gz for the 0.7.3 version, and not the .xpi. Which link on the releases page do I need to use?

Thank you for your help!

**Comment by jmozmoz** [comment]
You can find old XPI on addons.mozilla.org:
https://addons.mozilla.org/en-US/firefox/addon/tabpreloader/versions/
(on github there are no XPIs. Acutally, you also could not use them because they need to be signed by AMO to usable in Firefox).

Which version do you need?

**Comment by LafinJack** [comment]
Mozilla removed all non webextension versions of every addon a couple months ago with the API change. I'm using Waterfox and versions before 0.8.0 don't work. It looks like I'm looking for version 0.7.3 of the XPI version.

**Comment by LafinJack** [comment]
Can't edit, that should be the XUL version.
