### ISSUE TITLE
Describe the grace period as seconds

### ISSUE THREAD

**Issue by grahamperrin** [jmozmoz/tabPreLoader#7]
When I first opened preferences for the extension, I could not guess whether the value (5) was seconds or milliseconds. 

https://github.com/jmozmoz/tabPreLoader/commit/fab49da48e5aadb6881af7302cbd3de208690fa0#diff-7934bf411fea192ad8cd69e0a12911648a2842cb0f2409a8fb67b41b7069d757R37

**Comment by jmozmoz** [comment]
Should be fixed with the new version 0.8.3

**Comment by grahamperrin** [comment]
Thank you!
